/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResult"];
                        "application/json": components["schemas"]["AuthResult"];
                        "text/json": components["schemas"]["AuthResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserResponse"];
                        "application/json": components["schemas"]["UserResponse"];
                        "text/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/PriceHistories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePriceHistoryRequest"];
                    "text/json": components["schemas"]["CreatePriceHistoryRequest"];
                    "application/*+json": components["schemas"]["CreatePriceHistoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PriceHistoryResponse"];
                        "application/json": components["schemas"]["PriceHistoryResponse"];
                        "text/json": components["schemas"]["PriceHistoryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/PriceHistories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PriceHistoryResponse"];
                        "application/json": components["schemas"]["PriceHistoryResponse"];
                        "text/json": components["schemas"]["PriceHistoryResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePriceHistoryRequest"];
                    "text/json": components["schemas"]["UpdatePriceHistoryRequest"];
                    "application/*+json": components["schemas"]["UpdatePriceHistoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PriceHistoryResponse"];
                        "application/json": components["schemas"]["PriceHistoryResponse"];
                        "text/json": components["schemas"]["PriceHistoryResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/PriceHistories/subscription/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subscriptionId: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PriceHistoryResponse"][];
                        "application/json": components["schemas"]["PriceHistoryResponse"][];
                        "text/json": components["schemas"]["PriceHistoryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/SubscriptionCategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionCategoryResponse"][];
                        "application/json": components["schemas"]["SubscriptionCategoryResponse"][];
                        "text/json": components["schemas"]["SubscriptionCategoryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubscriptionCategoryRequest"];
                    "text/json": components["schemas"]["CreateSubscriptionCategoryRequest"];
                    "application/*+json": components["schemas"]["CreateSubscriptionCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionCategoryResponse"];
                        "application/json": components["schemas"]["SubscriptionCategoryResponse"];
                        "text/json": components["schemas"]["SubscriptionCategoryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/SubscriptionCategories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionCategoryResponse"];
                        "application/json": components["schemas"]["SubscriptionCategoryResponse"];
                        "text/json": components["schemas"]["SubscriptionCategoryResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubscriptionCategoryRequest"];
                    "text/json": components["schemas"]["UpdateSubscriptionCategoryRequest"];
                    "application/*+json": components["schemas"]["UpdateSubscriptionCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionCategoryResponse"];
                        "application/json": components["schemas"]["SubscriptionCategoryResponse"];
                        "text/json": components["schemas"]["SubscriptionCategoryResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionResponse"][];
                        "application/json": components["schemas"]["SubscriptionResponse"][];
                        "text/json": components["schemas"]["SubscriptionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubscriptionRequest"];
                    "text/json": components["schemas"]["CreateSubscriptionRequest"];
                    "application/*+json": components["schemas"]["CreateSubscriptionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionResponse"];
                        "application/json": components["schemas"]["SubscriptionResponse"];
                        "text/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionResponse"];
                        "application/json": components["schemas"]["SubscriptionResponse"];
                        "text/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubscriptionRequest"];
                    "text/json": components["schemas"]["UpdateSubscriptionRequest"];
                    "application/*+json": components["schemas"]["UpdateSubscriptionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionResponse"];
                        "application/json": components["schemas"]["SubscriptionResponse"];
                        "text/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResult: {
            succeeded?: boolean;
            token?: null | string;
            errors?: string[];
        };
        BillingInterval: number;
        CreatePriceHistoryRequest: {
            /** Format: double */
            price: number | string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: null | string;
            /** Format: int32 */
            subscriptionId: number | string;
        };
        CreateSubscriptionCategoryRequest: {
            title: string;
            description: null | string;
        };
        CreateSubscriptionRequest: {
            title: string;
            description: null | string;
            /** Format: double */
            price: number | string;
            billingInterval: components["schemas"]["BillingInterval"];
            /** Format: date-time */
            nextBillingDate: string;
            /** Format: int32 */
            subscriptionCategoryId: number | string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        PriceHistoryResponse: {
            /** Format: int32 */
            id: number | string;
            /** Format: double */
            price: number | string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: null | string;
            /** Format: int32 */
            subscriptionId: number | string;
        };
        RegisterRequest: {
            username: string;
            email: string;
            password: string;
        };
        SubscriptionCategoryResponse: {
            /** Format: int32 */
            id: number | string;
            title: string;
            description: null | string;
        };
        SubscriptionResponse: {
            /** Format: int32 */
            id: number | string;
            title: string;
            description: null | string;
            /** Format: double */
            price: number | string;
            billingInterval: components["schemas"]["BillingInterval"];
            /** Format: date-time */
            nextBillingDate: string;
            subscriptionCategoryResponse: components["schemas"]["SubscriptionCategoryResponse"];
        };
        UpdatePriceHistoryRequest: {
            /** Format: double */
            price: number | string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: null | string;
        };
        UpdateSubscriptionCategoryRequest: {
            title: string;
            description: null | string;
        };
        UpdateSubscriptionRequest: {
            title: string;
            description: null | string;
            /** Format: double */
            price: number | string;
            billingInterval: components["schemas"]["BillingInterval"];
            /** Format: date-time */
            nextBillingDate: string;
            /** Format: int32 */
            subscriptionCategoryId: number | string;
        };
        UserResponse: {
            userId: string;
            username: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
